import type { RuntimeIntentModel } from './types';

export const INTENT_MODEL: RuntimeIntentModel = {
  version: 'intent-heuristic-2025-11-07',
  createdAt: new Date().toISOString(),
  description: 'Heuristic classifier baseline for Riflett unified intent taxonomy.',
  labels: [
    { id: 'conversational', display: 'Conversational', subsystem: 'entries' },
    { id: 'entry_create', display: 'Entry Create', subsystem: 'entries' },
    { id: 'entry_discuss', display: 'Entry Discuss', subsystem: 'entries' },
    { id: 'entry_append', display: 'Entry Append', subsystem: 'entries' },
    { id: 'command', display: 'Command', subsystem: 'user_config' },
    { id: 'search_query', display: 'Search Query', subsystem: 'knowledge' },
  ],
  logPriors: {
    conversational: Math.log(0.35),
    entry_create: Math.log(0.25),
    entry_discuss: Math.log(0.1),
    entry_append: Math.log(0.1),
    command: Math.log(0.1),
    search_query: Math.log(0.1),
  },
  tokenLogLikelihoods: {
    conversational: {
      why: -3.4,
      how: -3.6,
      think: -3.8,
      feel: -3.5,
      anxious: -4.0,
      stuck: -4.0,
      should: -3.9,
      maybe: -3.9,
      unsure: -3.8,
      explain: -3.7,
    },
    entry_create: {
      today: -3.3,
      just: -3.4,
      finished: -3.5,
      decided: -3.5,
      save: -3.2,
      log: -3.2,
      capture: -3.3,
      remember: -3.4,
      time: -3.6,
      am: -3.7,
      pm: -3.7,
      minutes: -3.8,
      meeting: -3.8,
      call: -3.9,
    },
    entry_discuss: {
      about: -3.5,
      regarding: -3.5,
      what: -3.6,
      if: -3.8,
      it: -3.4,
      this: -3.4,
      that: -3.5,
      plan: -3.8,
      goal: -3.6,
      entry: -3.6,
    },
    entry_append: {
      also: -3.2,
      update: -3.4,
      forgot: -3.4,
      mention: -3.4,
      another: -3.5,
      plus: -3.5,
      adding: -3.5,
      note: -3.5,
    },
    command: {
      '/goal': -2.5,
      '/journal': -2.5,
      '/schedule': -2.5,
      '/reflect': -2.5,
      '/patterns': -2.5,
      '/mood': -2.5,
      '/review': -2.5,
      '/search': -2.5,
      create: -3.3,
      show: -3.6,
      set: -3.6,
    },
    search_query: {
      find: -3.0,
      show: -3.2,
      search: -3.1,
      when: -3.3,
      where: -3.4,
      wrote: -3.4,
      entries: -3.5,
      about: -3.5,
      list: -3.4,
      look: -3.6,
    },
  },
  unseenTokenPenalty: Math.log(0.05),
  vocabularySize: 512,
  alpha: 1.0,
  topFeatures: {
    conversational: ['why', 'how', 'feel', 'think'],
    entry_create: ['today', 'save', 'log', 'capture'],
    entry_discuss: ['what', 'about', 'regarding', 'it'],
    entry_append: ['also', 'update', 'forgot', 'another'],
    command: ['/goal', '/journal', 'create', '/search'],
    search_query: ['find', 'show', 'search', 'when'],
  },
};
